### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by matiazar** [Kolovious/MeliSocialite#1]
Gracias por el aporte. Se puede instalar en Laravel 5.1 sin problemas?

gracias nuevamente

**Comment by kolovious** [comment]
Que tal Matias, mira supongo no deberias tener inconveniente ya que es muy simple yo creeria que si.

Si te surge algun inconveniente hacemelo saber o hace un pull request

**Comment by matiazar** [comment]
gracias por responder. en realidad no me deja instalar el paquete porq el composer.json dice que requiere laravel 5.2, podrias cambiarlo a 5.\* o yo investigar como saltear dicha validacion ! ja

 "require": {
        "illuminate/support": "^5.2"
    },

**Comment by kolovious** [comment]
Ahi esta cambiado, confirmame que la pudiste instalar correctametne

**Comment by matiazar** [comment]
Hola no, puse 
composer require kolovious/melisocialite

y me dice q baja la version 0.18 y requiere illuminate/support v5.2.25

**Comment by kolovious** [comment]
ok, dejame verlo que evidentemente cambiando el composer.json y haciendo el push al proyecto no lo toma, estoy aprendiendo a usar el git aun

**Comment by matiazar** [comment]
dale. muchas gracias.

**Comment by kolovious** [comment]
Si haces un request del dev-master te funciona?

**Comment by matiazar** [comment]
si!

agregando asi a mi composer.json y ejecutando, composer update, me lo bajo perfectamente.
    "require": {
        "kolovious/melisocialite": "dev-master"
    },
