### ISSUE TITLE
 RequestException

### ISSUE THREAD

**Issue by aleporf** [Kolovious/MeliSocialite#4]
Buenas puedes ayudarme con este error?

Client error: `POST https://api.mercadolibre.com/oauth/token` resulted in a `400 Bad Request` response:
{"message":"Wrong number of parameters","error":"invalid_request","status":400,"cause":[]}
gracias!

**Comment by kolovious** [comment]
Hola, deberias poner el contexto en que lo estas usando, esta claro que le falta algun parametro, pero hay que ver cual.

**Comment by aleporf** [comment]
Hola, Lean gracias por tu respuesta. 
El problema es cuando uso GET

	//publications
   		$userMeli = Socialite::driver('meli')->user();
    	        $offset = 10;
		$call= "/users/252012768/items/search";
		$result = Meli::get($call, ["offset"=>$offset, 'access_token'=>$userMeli->token]);

======

Creo que el error viene de aca MeliSocialite.php


    protected function getTokenFields($code)
    {
        return [
            'client_id' => $this->clientId, 'client_secret' => $this->clientSecret,
            'grant_type'=>'authorization_code',
            'code' => $code, 'redirect_uri' => $this->redirectUrl,
        ];
    }

Abrazo!

**Comment by kolovious** [comment]
Tenes corroborado que el client_id y el client_secret de tu codigo esta pasando en el post?

**Comment by aleporf** [comment]
Entiendo que si ya que el auth y permisos del usuario<-> funciona perfectamente,

**Comment by kolovious** [comment]
Ok, para que entienda. El error por el que creas el issue es en oauth/token, como bad request. A esa direccion se pide el refresh token.

Tenes comportamiento erratico o siempre te falla? 
Despues me pones que el error te lo da en un get a un listado de un usuario.

**Comment by aleporf** [comment]
Perdón sino se entendió: El auth con meli funciona perfectamente, el problema es cuando hago el GET por esto no estoy entendiendo que esta pasando. 

Mil Gracias nuevamente. 

Si aun así no queda claro te puedo compartir el proyecto

**Comment by kolovious** [comment]
OK, cuando haces el get a meli que te devuelve? Porque es muy simple si tenes el access_token correcto. Mostrame el json de lo que te devuelve.

**Comment by aleporf** [comment]
cuando ejecuto esta linea fuera de handleProviderCallback()
        $user = Socialite::driver('meli')->user();
aparece el siguiente error: 

  FatalErrorException in MeliSocialite.php line 128:
  Class 'Kolovious\MeliSocialite\InvalidStateException' not found

perdon por las idas y vueltas

**Comment by kolovious** [comment]
es porque estas intentando armar la sesion con un codigo que no sirve. Pone el link para ir a hacer login con ML y usalo de nuevo y no sale. Una vez que obtenes el codigo, persistilo en una base de datos y luego nunca mas le tenes que pedir login utilizando correctamente el refresh token cuando esta vencido.

**Comment by aleporf** [comment]
me podrias orientar un poco mas? muchas gracias

**Comment by aleporf** [comment]
Resuelto!!! gracias lean.
