### ISSUE TITLE
problema con parametros

### ISSUE THREAD

**Issue by aleporf** [Kolovious/MeliSocialite#5]
Hola, como andas? no puedo filtrar por preguntas NO RESPONDIDAS. Si hago el curl en terminal funciona perfectamente. 

Abrazo!

$offset = 0;                                            
$call= "/my/received_questions/search?status=unanswered";
                                                                 ================
$result = Meli::get($call, ["offset"=>$offset, 'access_token'=>$findUser->token]);

//devuelve
{"body":{"message":"Invalid status {0}.","error":"invalid_status_search","status":400,"cause":[]},"httpCode":400}

**Comment by kolovious** [comment]
Disculpa el cuelgue, este error no se si esta relacionado con el Meli::get, creo que esta relacionado con el api call.

Cualquier cosa volve a abrir este issue
