### ISSUE TITLE
POST recurso Items

### ISSUE THREAD

**Issue by canizalezDaniel** [Kolovious/MeliSocialite#6]
Hola estimado, gracias! preguntó si este repo me permitirá realizar publicaciones de productos a través del recurso items de MELI:

https://api.mercadolibre.com/items?access_token="" 

{
"title":"Item de test - No Ofertar",
"category_id":"MLC3530",
"price":10,
"currency_id":"CLP",
"available_quantity":5,
"buying_mode":"buy_it_now",
"listing_type_id":"bronze",
"description": "Item de test - No Ofertar",
"condition": "used",
"pictures":[{"source":"http://santanaelectricalservice.com.ve/imagenes/importamostodo.jpg"}]
	
}

Gracias.

**Comment by kolovious** [comment]
Como va? Claro que podes hacer eso. 
Vos podes hacer

```php
$result = Meli::withToken($token)->post('/items/', [ 
    'title' => 'Item de test - No Ofertar',
    'category_id'=>'MLC3530',
]);
```

**Comment by canizalezDaniel** [comment]
Bueno estoy nuevo en esto, gracias.

Resulta que siempre me lanza hacia http://localhost:8000/auth/meli/callback?code=TG-5a8b8702e4b0566390f17dec-296965123&state=HFJ3QlGsjeK6JcEf2mbMuP9RRFNEQQnj1MX7WdK3

con una pagina en blanco. Mi configuración parece todo bien. 

'client_id' => 'miclient_id',
        'client_secret' => 'miclient_secret',
        'redirect' => 'http://localhost:8000/auth/meli/callback',

**Comment by canizalezDaniel** [comment]
Ya resolvi amigo. Muchas gracias estoy tratando de realizar un post hacia MELI desde un API y este ayudo muchisimo!

**Comment by canizalezDaniel** [comment]
Buenas tardes amigos, pregunto y no se si deba abrir un nuevo issues para ello pero pretento utilizar este repo tambien para realizar post a Mercadolibre CBT cambiando 

public static $API_ROOT_URL = "https://cbt.mercadolibre.com";
public static $AUTH_URL     = "https://cbt.mercadolibre.com/merchant/authorization";
public static $OAUTH_URL    = "/oauth/token";

Pero al autenticar, me devuelve un error 

Laravel \ Socialite \ Two \ InvalidStateException
No message

Es posible que pueda reutilizar el código para Mercadolibre CBT?

**Comment by kolovious** [comment]
mira, la actualizacion del api de Mercadolibre tiene una forma nueva de armar este auth_url.

Igual creo que el api root creo siempre es api.mercadolibre.com, alli esta el repositorio central. Luego el auth es por pais.

Probalo y me decis.

**Comment by canizalezDaniel** [comment]
Si, pero creo que CBT http://cbt.mercadolibre.com/ me comentaron y enviaron un manual donde la autorización es https://cbt.mercadolibre.com/merchant/authorization/?client_id=XXXXXX&response_type=code&redirect_uri=XXXXXX

Yo logro realizar POST y consultas por País pero entiendo que CBT es algo general de ML sin localizar por país. Para publicaciones en varios países.

Quería reutilizar su repo colocando el API ROOT URL y AUTH URL del CBT pero me devuelve ese mensaje de error.

Saludos.

**Comment by kolovious** [comment]
La autorizacion si es local, pero la llamada al api es unica. Corroboraste eso?

**Comment by canizalezDaniel** [comment]
Listo resuelto use el token devuelto por cbt con el api root y auth url de cbt, gracias.

**Comment by price2b** [comment]
> Listo resuelto use el token devuelto por cbt con el api root y auth url de cbt, gracias.

@canizalezDaniel podrias compartir como quedo el codigo para ser usado con mercadolibre cbt? Gracias!

**Comment by canizalezDaniel** [comment]
Deje el codigo hace buen rato, encontre algo creo que fue aplicado una prueba 

1 usando MeliSocialite rescato $token = Socialite::driver('meli')->user();
2 armo el SKU de meli de acuerdo a la documentación: $SKU_MELI=str_pad($product['created_at']->getTimestamp()+1, $longitud, '0', STR_PAD_LEFT);
3 armo una lista de atributos a pasar al cbt ejemplo:  $lalista['product_title_english'] = $product->Title;
4 mando un curl:
 $curl = curl_init();

         curl_setopt_array($curl, array(
           CURLOPT_URL => "https://cbt.mercadolibre.com/api/SKUs/?access_token=$token",
           CURLOPT_RETURNTRANSFER => true,
           CURLOPT_ENCODING => "",
           CURLOPT_MAXREDIRS => 10,
           CURLOPT_TIMEOUT => 30,
           CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
           CURLOPT_CUSTOMREQUEST => "POST",
           CURLOPT_POSTFIELDS => json_encode($lalista),
           CURLOPT_HTTPHEADER => array(
             "Cache-Control: no-cache",
             "Content-Type: application/json"
           ),
         ));
y wala!

con eso funcionaria, luego recuerdo hice otras cosas pero allí quedo algo/

**Comment by canizalezDaniel** [comment]
> > Listo resuelto use el token devuelto por cbt con el api root y auth url de cbt, gracias.
> 
> @canizalezDaniel podrias compartir como quedo el codigo para ser usado con mercadolibre cbt? Gracias!

@price2b estimado, algo quedo del codigo que deje hace rato pude aplicar un curl
rescato el token usando MeliSocialite y se lo paso con una lista en JSON de los atributos a enviar al CBT
Ejemplo:  $list['product_title_english'] = $product->Title;
curl_setopt_array($curl, array(
           CURLOPT_URL => "https://cbt.mercadolibre.com/api/SKUs/?access_token=$token",
           CURLOPT_RETURNTRANSFER => true,
           CURLOPT_ENCODING => "",
           CURLOPT_MAXREDIRS => 10,
           CURLOPT_TIMEOUT => 30,
           CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
           CURLOPT_CUSTOMREQUEST => "POST",
           CURLOPT_POSTFIELDS => json_encode($list),
           CURLOPT_HTTPHEADER => array(
             "Cache-Control: no-cache",
             "Content-Type: application/json"
           ),
         ));

**Comment by price2b** [comment]
@canizalezDaniel muchas gracias!, voy a intentar por ese lado. Cordiales saludos!.
