### ISSUE TITLE
Error Authentificando Meli

### ISSUE THREAD

**Issue by gonzalo-b** [Kolovious/MeliSocialite#8]
Estoy teniendo problemas para trabajar el repeo

Segui todos los pasos y al ejecutar:

  $user = Socialite::driver('meli')->user();

Me devuelve:
![image](https://user-images.githubusercontent.com/3964296/40455274-9c81302e-5ec2-11e8-864c-8ff2a5f2cf19.png)

Alguna idea que podra ser?

**Comment by kolovious** [comment]
Hola, voy a ver si puedo agregar un ejemplo real de uso, vi que varias personas que quicieron usar la libreria se encontraron con e mismo problema. 

Agregar como extender la clase User y como poner los metodos para que exista el metodo de login con Meli.

Debes estar utilizando mal el flow, esa Exception te la devuelve cuando estas usando un codigo viejo para conectar con el usuario.

Si el usuario no esta logueado lo redireccionas con el socialite? Pusiste muy poco de tu flow de como haces par mandar.

**Comment by gonzalo-b** [comment]
Gracias! Lo pude hacer funcionar!
