### ISSUE TITLE
ejemplo basico como redireccionar un usuario.

### ISSUE THREAD

**Issue by price2b** [Kolovious/MeliSocialite#9]
hola!,

estoy utilizando el ejemplo basico. 
1- cree un controlador para AuthController (ya que uso una libreria distinta al tradicional https://github.com/jeremykenedy/laravel-auth)
2- cree las rutas para AuthController.
3- cree la siguiente funcion y su ruta.

```
    public function index()
    {
        
        $user = Socialite::driver('meli')->user();

// Tokens & Expire time
        $token         = $user->token;
        $refresh_token = $user->refresh_token;
        $expires_at    = $user->expires_at; // UNIX TIMESTAMP

// Methods from Socialite User
        $user->getId();
        $user->getNickname();
        $user->getName();
        $user->getEmail();

// Raw Data
        $user->user;
    }
```
Pero recibo el error siguiente en el archivo melisocialite/src/MeliSocialite.php

```
public function user()
    {
        if ($this->hasInvalidState()) {
            throw new InvalidStateException;
        }
 
```
No comprendo si debo generar un redireccionamiento en el controlador o si al llamar a Socialite::driver('meli')->user(); el codigo hace un redireccionamiento al login de MELI.

Disculpas si no es claro pero es lo que entendi hasta ahora.. gracias.

**Comment by kolovious** [comment]
No se como se combina esa libreria laravel auth con el laravel socialite que ya tiene incorporado todo lo que son los social auth.
El es quien se ocupa de redireccionar si no tenes el usuario valido.

Como usas el socialite con ese auth propio?

**Comment by kolovious** [comment]
En la explicacion de como usar ese laravel-auth dice como usarlo

Add the social media login link:

Example: In file /resources/views/auth/login.blade.php add ONE of the following:

Conventional HTML:
<a href="{{ route('social.redirect', ['provider' => 'twitch']) }}" class="btn btn-lg btn-primary btn-block twitch">Twitch</a>
Use Laravel HTML Facade with Laravel Collective:
{!! HTML::link(route('social.redirect', ['provider' => 'twitch']), 'Twitch', array('class' => 'btn btn-lg btn-primary btn-block twitch')) !!}

Ahi tenes que poner en provider=>'meli'
Y obviamente tener configuradas las credenciales de meli de tu app.

**Comment by price2b** [comment]
Muchas gracias, perdon la demora pero estuve fuera gran parte del dia. Esa era mi consulta, si se integra como otro proveedor de acceso a la plataforma (como facebook, twitter, linkedin) y realiza el login del usuario directamente a toda la aplicacion. Y de ahi realiza la redireccion cuando el usuario ingresa a un lugar que precisa login.

Muchas gracias por tu tiempo y ayuda, voy a intentar eso. saludos!
